### ISSUE TITLE
时不时会无法正常弹框

### ISSUE THREAD

**Issue by xiaoyaoyou** [hcfyapp/crx-selection-translate#1851]
## 基本信息

划词翻译版本：10.1.2
浏览器版本：115.0.5790.114
操作系统：macOS Monterey

## 重现问题的步骤
最近在使用划词翻译的时候，经常会出现翻译弹框出现后马上自己消失，然后再划词就不能再触发弹框了，需要重新刷新整个网页才能正常工作，但是有的时候刷新完后还是继续出现这个问题
1. 比如打开该页面：https://github.com/xorbitsai/inference
2. 对右侧about部分的「inference」单词进行划词操作
3. 

### 预期行为
翻译弹框正常显
### 实际行为
弹框有的时候会消失，然后在该页面就不能再正常使用划词翻译软件了，需要重新刷新页面，有的时候刷新完后还是继续出现这个问题
### 补充信息

以下应该是弹框消失是在console窗口出现的错误堆栈信息：
`847.js:2 TypeError: Cannot read properties of undefined (reading 'join')
    at 704.js:1:15839
    at Array.map (<anonymous>)
    at R (704.js:1:15810)
    at _a (847.js:2:240996)
    at Tl (847.js:2:252627)
    at _u (847.js:2:298718)
    at ws (847.js:2:287003)
    at ys (847.js:2:286931)
    at gs (847.js:2:286794)
    at as (847.js:2:283601)
dl @ 847.js:2
n.callback @ 847.js:2
Bi @ 847.js:2
xu @ 847.js:2
wu @ 847.js:2
bu @ 847.js:2
(anonymous) @ 847.js:2
ks @ 847.js:2
is @ 847.js:2
k @ 847.js:2
O @ 847.js:2
Show 11 more frames
Show less
847.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'join')
    at 704.js:1:15839
    at Array.map (<anonymous>)
    at R (704.js:1:15810)
    at _a (847.js:2:240996)
    at Tl (847.js:2:252627)
    at _u (847.js:2:298718)
    at ws (847.js:2:287003)
    at ys (847.js:2:286931)
    at gs (847.js:2:286794)
    at as (847.js:2:283601)`

**Comment by lmk123** [comment]
见公告 https://hcfy.app/blog/2023/09/13/ggcrash
