### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.

### ISSUE THREAD

**Issue by meinjoy** [hcfyapp/crx-selection-translate#1950]
我们正在开发的网站有一个textarea,当输入多行信息后,用鼠标从顶部划到底部全选textarea中的内容时,浏览器的console会报错:
删除划词翻译插件后正常,不报错

228.js:1 Uncaught DOMException: Failed to execute 'setEnd' on 'Range': There is no child at offset 1.
    at d (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/228.js:1:7448)
    at B (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/228.js:1:8015)
    at p (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/228.js:1:9248)
    at I.sendMsg (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/228.js:1:11813)
    at Object.getInfoSync (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/975.js:1:51665)
    at Object.sendMsg (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/975.js:1:50851)
    at chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/975.js:1:49807
    at I.postMsgToTopmostFrame (chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/228.js:1:9742)
    at chrome-extension://ikhdkkncnoglghljlkmcimlnlhkeamad/228.js:1:10142

划词翻译版本：v10.5.1
浏览器版本：版本 121.0.6167.140（正式版本） （64 位）
操作系统：win11 联想2023 thinkbook oem 家庭版

![bug](https://github.com/hcfyapp/crx-selection-translate/assets/49466588/1fdae218-05d6-4e61-ac86-63c849c90f00)

**Comment by lmk123** [comment]
感谢反馈，翻了一下发现其实去年就有人反馈这个问题了 :joy: 我提升一下优先级 

- #1445
